name: logtek_gi
description: Logtek G&I (Gestion & Inventaire) — Flutter starter
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  crypto: ^3.0.3

  # Réseau / utilitaires
  http: ^1.2.2
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.3.0
  # Auth + DB
  supabase_flutter: ^2.5.6
  connectivity_plus: ^6.0.5
  path_provider: ^2.1.4
  sqflite: 2.2.8+4
  path: ^1.9.0
  flutter_dotenv: ^5.1.0
  speech_to_text: ^6.3.0
  image_picker: ^1.0.7
  # Notifications locales (sans Firebase)
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logtek_logo_flat.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logtek_logo.png
    - assets/images/logtek_logo_flat.png
    - .env
